name: QuickbarPlugin
main: com.gmail.leal.mendo.QuickbarPlugin.QuickbarPlugin
version: 1.0
author: agrendath
api-version: 1.16
softdepend: [mcMMO]
commands:
  tiago:
    description: Returns useful information about tiago
    usage: /tiago
    permission: quickbarplugin.tiago
    permission-message: You don't have permission to use this extremely powerful command
  emma:
    description: Gives the player the quickbar switching tool
    usage: /emma
    permission: quickbarplugin.emma
    permission-message: You don't have permission for that
  emma2:
    description: Converts xp into xp bottles
    usage: /emma2 <amount of bottles>
    permission: quickbarplugin.emma2
    permission-message: You don't have permission for that
  janita:
    description: Return the amount of deaths for a specific player
    usage: /janita <playername>
    permission: quickbarplugin.janita
    permission-message: You don't have permission for that
  janita2:
    description: Return the amount of apples eaten for a specific player
    usage: /janita2 <playername>
    permission: quickbarplugin.janita2
    permission-message: You don't have permission for that
  lucas:
    description: Returns useful information about lucas
    usage: /lucas
    permission: quickbarplugin.lucas
    permission-message: You don't have permission to use this extremely powerful command
  souls:
    description: Returns your tiago souls balance or lets you give souls to another player
    usage: /souls give <player> <amount>
    permission: quickbarplugin.souls
    permission-message: You don't have permission to manipulate tiago souls
  soulenchant:
    description: Enchants the item in your hand with a soul enchantment, available enchantments are magnetism and indestructibility
    usage: /soulenchant <enchantment>
    permission: quickbarplugin.soulenchant
    permission-message: You don't have permission to enchant items with tiago souls
  janitatop:
    description: Shows a leaderboard of the top 10 player's deaths
    usage: /janitatop
    permission: quickbarplugin.janitatop
    permission-message: You don't have permission for that
  janita2top:
    description: Shows a leaderboard of the top 10 player's apples eaten
    usage: /janita2top
    permission: quickbarplugin.janita2top
    permission-message: You don't have permission for that
  extract:
    description: Extracts an enchantment from an item and gives it to the player in enchanted book form, does not work for soul enchantments
    usage: /extract <enchantment>
    permission: quickbarplugin.extract
    permission-message: You don't have permission for that
  booster:
    description: Gives the player a booster for the given McMMO Skill
    usage: /booster <skill> [amount]
    permission: quickbarplugin.booster
    permission-message: You don't have permission for that
  activebooster:
    description: Informs the player of whether they have a booster enabled and if so of which type and how much remaining xp it has
    usage: /activebooster
    permission: quickbarplugin.activebooster
    permission-message: You don't have permission for that